name: Check for Updates

on:
  schedule:
    - cron: "58 5 * * *"
  workflow_dispatch:

jobs:
  version-check:
    name: Compare Local and Upstream Versions
    runs-on: ubuntu-24.04
    permissions: write-all
    outputs:
      update_required: ${{ steps.compare_versions.outputs.update_required }}
      current_version: ${{ steps.get_release_version.outputs.current_version }}
      upstream_version: ${{ steps.get_upstream_version.outputs.upstream_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get current version
        id: get_current_version
        run: |
          echo "Getting current version"
          ls -A
          git status
          CURRENT_VERSION=$(git describe --tags --abbrev=0)
          echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get upstream version
        id: get_upstream_version
        run: |
          set -e
          echo "Getting upstream version"
          UPSTREAM_VERSION=$(wget -q "https://launchpad.net/ubuntu/noble/amd64/mariadb-server" -O - | grep '<a href="/ubuntu/noble/amd64/mariadb-server' | head -n 1 | sed 's/.*">1://;s/-.*//')
          echo "Upstream version: $UPSTREAM_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "upstream_version=$UPSTREAM_VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare_versions
        env:
          CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
          UPSTREAM_VERSION: ${{ steps.get_upstream_version.outputs.upstream_version }}
        run: |
          set -e
          echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$UPSTREAM_VERSION" | sed 's/^v\+//' | sort -V | tail -n 1)" == "$CURRENT_VERSION" ]; then
              echo "Current version $CURRENT_VERSION is greater than or equal to Upstream version $UPSTREAM_VERSION."
              echo "No update required." >> $GITHUB_STEP_SUMMARY
              echo "update_required=false" >> $GITHUB_OUTPUT
          else
              echo "Upstream version $UPSTREAM_VERSION is newer than Current version $CURRENT_VERSION."
              echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
              echo "update_required=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: ${{ steps.compare_versions.outputs.update_required }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NEW_VERSION: ${{ steps.get_upstream_version.outputs.upstream_version }}
        with:
          tag_name: v${{ steps.get_upstream_version.outputs.upstream_version }}
          body: MariaDB server version bump
          generate_release_notes: true
          append_body: true
          make_latest: true
